### ISSUE TITLE
Make the runner nugettable

### ISSUE THREAD

**Issue by DerAlbertCom** [JonathanWilkins/machine.vstestadapter#17]
Hi,

the xUnit Runner for Visual Studio is installable via Nuget and don't need as vsix. the good thing about it, everyone has automaticly the runner without installing something. and it also works in tfs and visual studio online.

https://github.com/xunit/visualstudio.xunit

**Comment by JonathanWilkins** [comment]
Thanks, will take a look and see what I can do

**Comment by JonathanWilkins** [comment]
Hi 

What did you have to do to get it to run in as a nuget package?
Is there anything special you need to do, is it simply making sure you have all the right references.

**Comment by DerAlbertCom** [comment]
I don' know, thats why i pointing to the xunit repository ;)

Maybe it is as simple as having the assembly in the project referenced.

**Comment by JonathanWilkins** [comment]
I'm going to close this now as it has been sorted, thanks @ivanz 
Nuget Package is Machine.VSTestAdapter.
